# Generated by Django 5.0.6 on 2024-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="uploads/product/default.jpg", upload_to="uploads/product/"
            ),
        ),
    ]
