# Generated by Django 5.0.6 on 2024-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="uploads/product/"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
