# Generated by Django 5.0.6 on 2024-08-24 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_remove_product_price_product_painting_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="painting_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="print_price",
        ),
    ]
